server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: audio
          uri: lb://AUDIO
          predicates:
            - Path=/api/v1/resources/**
        - id: metadata
          uri: lb://METADATA
          predicates:
            - Path=/api/v1/**


  output:
    ansi:
      enabled: always
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka